# Generated by Django 5.0 on 2025-11-29 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('systems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('low', 'Oddiy'), ('medium', "O'rtacha"), ('high', 'Yuqori')], default='medium', max_length=10, verbose_name='Ustuvorlik')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('in_progress', 'Jarayonda'), ('pending_approval', 'Hal qilindi (kutilmoqda)'), ('resolved', 'Hal qilindi'), ('rejected', 'Rad etildi'), ('reopened', 'Qayta ochildi')], default='new', max_length=20, verbose_name='Holat')),
                ('description', models.TextField(verbose_name="Muammo ta'rifi")),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tickets/attachments/', verbose_name='Fayl biriktirma')),
                ('rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Baholash')),
                ('rating_comment', models.TextField(blank=True, verbose_name='Baholash izohi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan")),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Hal qilingan vaqt')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name="Mas'ul xodim")),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='accounts.region', verbose_name='Viloyat')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='systems.system', verbose_name='Tizim')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Murojaat',
                'verbose_name_plural': 'Murojaatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('created', 'Yaratildi'), ('status_changed', "Holat o'zgartirildi"), ('assigned', "Mas'ul biriktirildi"), ('reassigned', "Mas'ul o'zgartirildi"), ('comment', "Izoh qo'shildi"), ('reopened', 'Qayta ochildi'), ('rated', 'Baholandi'), ('file_attached', 'Fayl biriktirildi')], max_length=20, verbose_name='Harakat turi')),
                ('old_value', models.CharField(blank=True, max_length=200, verbose_name='Eski qiymat')),
                ('new_value', models.CharField(blank=True, max_length=200, verbose_name='Yangi qiymat')),
                ('message', models.TextField(blank=True, verbose_name='Izoh')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_changes', to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tickets.ticket', verbose_name='Murojaat')),
            ],
            options={
                'verbose_name': 'Murojaat tarixi',
                'verbose_name_plural': 'Murojaat tarixlari',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tickets/chat_attachments/', verbose_name='Fayl')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_messages', to=settings.AUTH_USER_MODEL, verbose_name='Yuboruvchi')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tickets.ticket', verbose_name='Murojaat')),
            ],
            options={
                'verbose_name': 'Chat xabari',
                'verbose_name_plural': 'Chat xabarlari',
                'ordering': ['created_at'],
            },
        ),
    ]
