# Generated by Django 5.0 on 2025-12-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assignment_type',
            field=models.CharField(blank=True, choices=[('auto', 'Avtomatik'), ('self', "O'zi oldi"), ('admin', 'Admin biriktirdi')], default='auto', max_length=20, verbose_name='Biriktirilish turi'),
        ),
    ]
