# Generated by Django 5.0 on 2025-11-29 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Tizim nomi')),
                ('description', models.TextField(blank=True, verbose_name="Ta'rif")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'Tizim',
                'verbose_name_plural': 'Tizimlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemResponsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_system', models.CharField(choices=[('admin', 'Admin'), ('technician', 'Texnik xodim')], max_length=20, verbose_name='Rol')),
                ('is_default', models.BooleanField(default=False, help_text="Region bo'sh va is_default=True bo'lsa - respublika mas'uli", verbose_name="Asosiy mas'ul")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('region', models.ForeignKey(blank=True, help_text="Agar bo'sh bo'lsa - respublika miqyosida mas'ul", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_responsibles', to='accounts.region', verbose_name='Viloyat')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibles', to='systems.system', verbose_name='Tizim')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_responsibilities', to=settings.AUTH_USER_MODEL, verbose_name='Xodim')),
            ],
            options={
                'verbose_name': "Tizim mas'uli",
                'verbose_name_plural': "Tizim mas'ullari",
                'ordering': ['system', 'region'],
                'unique_together': {('system', 'user', 'region')},
            },
        ),
    ]
